language: go

addons:
  postgresql: "9.4"

services:
  - postgresql

go:
  - 1.7

before_install:
  - go install -a -race std
  - export PATH=$HOME/gopath/bin:$PATH
  - createdb tugboat
  - go install ./cmd/...
  - tugboat migrate

script:
  - make cmd
  - go test -race ./...
