test:
  adapter: postgresql
  database: deployer_test
  encoding: utf8
  pool: 5
  min_messages: warning

development:
  adapter: postgresql
  database: deployer_development
  encoding: utf8
  pool: 5
  min_messages: warning
