test:
  adapter: postgresql
  database: shipr_test
  encoding: utf8
  pool: 5
  min_messages: warning

development:
  adapter: postgresql
  database: shipr_development
  encoding: utf8
  pool: 5
  min_messages: warning
