development:
  sessions:
    default:
      database: shipr_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: shipr_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
